# makefile for showletter
#
# DFP, 8 Apr 2014

showletter: showletter.c
	gcc -Wall -o showletter -g showletter.c


# DO NOT DELETE

showletter: /usr/include/stdio.h /usr/include/features.h
showletter: /usr/include/stdc-predef.h /usr/include/sys/cdefs.h
showletter: /usr/include/bits/wordsize.h /usr/include/gnu/stubs.h
showletter: /usr/include/bits/types.h /usr/include/bits/typesizes.h
showletter: /usr/include/libio.h /usr/include/_G_config.h
showletter: /usr/include/wchar.h /usr/include/bits/stdio_lim.h
showletter: /usr/include/bits/sys_errlist.h /usr/include/stdlib.h
showletter: /usr/include/bits/waitflags.h /usr/include/bits/waitstatus.h
showletter: /usr/include/endian.h /usr/include/bits/endian.h
showletter: /usr/include/bits/byteswap.h /usr/include/bits/byteswap-16.h
showletter: /usr/include/sys/types.h /usr/include/time.h
showletter: /usr/include/sys/select.h /usr/include/bits/select.h
showletter: /usr/include/bits/sigset.h /usr/include/bits/time.h
showletter: /usr/include/sys/sysmacros.h /usr/include/bits/pthreadtypes.h
showletter: /usr/include/alloca.h /usr/include/bits/stdlib-float.h
showletter: Chars/All_Chars.h Chars/Char_20.h Chars/Char_21.h
showletter: Chars/Char_22.h Chars/Char_23.h Chars/Char_24.h Chars/Char_25.h
showletter: Chars/Char_26.h Chars/Char_27.h Chars/Char_28.h Chars/Char_29.h
showletter: Chars/Char_2A.h Chars/Char_2B.h Chars/Char_2C.h Chars/Char_2D.h
showletter: Chars/Char_2E.h Chars/Char_2F.h Chars/Char_30.h Chars/Char_31.h
showletter: Chars/Char_32.h Chars/Char_33.h Chars/Char_34.h Chars/Char_35.h
showletter: Chars/Char_36.h Chars/Char_37.h Chars/Char_38.h Chars/Char_39.h
showletter: Chars/Char_3A.h Chars/Char_3B.h Chars/Char_3C.h Chars/Char_3D.h
showletter: Chars/Char_3E.h Chars/Char_3F.h Chars/Char_40.h Chars/Char_41.h
showletter: Chars/Char_42.h Chars/Char_43.h Chars/Char_44.h Chars/Char_45.h
showletter: Chars/Char_46.h Chars/Char_47.h Chars/Char_48.h Chars/Char_49.h
showletter: Chars/Char_4A.h Chars/Char_4B.h Chars/Char_4C.h Chars/Char_4D.h
showletter: Chars/Char_4E.h Chars/Char_4F.h Chars/Char_50.h Chars/Char_51.h
showletter: Chars/Char_52.h Chars/Char_53.h Chars/Char_54.h Chars/Char_55.h
showletter: Chars/Char_56.h Chars/Char_57.h Chars/Char_58.h Chars/Char_59.h
showletter: Chars/Char_5A.h Chars/Char_5B.h Chars/Char_5C.h Chars/Char_5D.h
showletter: Chars/Char_5E.h Chars/Char_5F.h Chars/Char_60.h Chars/Char_61.h
showletter: Chars/Char_62.h Chars/Char_63.h Chars/Char_64.h Chars/Char_65.h
showletter: Chars/Char_66.h Chars/Char_67.h Chars/Char_68.h Chars/Char_69.h
showletter: Chars/Char_6A.h Chars/Char_6B.h Chars/Char_6C.h Chars/Char_6D.h
showletter: Chars/Char_6E.h Chars/Char_6F.h Chars/Char_70.h Chars/Char_71.h
showletter: Chars/Char_72.h Chars/Char_73.h Chars/Char_74.h Chars/Char_75.h
showletter: Chars/Char_76.h Chars/Char_77.h Chars/Char_78.h Chars/Char_79.h
showletter: Chars/Char_7A.h Chars/Char_7B.h Chars/Char_7C.h Chars/Char_7D.h
showletter: Chars/Char_7E.h
