/* Char_7A.h - Lower-Case z
 *
 * D Provine, 20 Mar 2012
 * Greg Richards 
 * $Id: $
 */

const byte Char_7A[10] = {
    0x00,     // ........
    0x00,     // ........
    0x00,     // ........
    0x7E,     // .XXXXXX.
    0x04,     // .....X..
    0x08,     // ....X...
    0x10,     // ...X....
    0x7E,     // .XXXXXX.
    0x00,     // ........
    0x00      // ........
};

